### ISSUE TITLE
Dose this module work in service worker?

### ISSUE THREAD

**Issue by JiaJiaJiang** [johanholmerin/worker-webrtc#1]
I'm happy to meet this polyfill, but i'm not sure if the module works in service worker cause nowhere mentioned it.

**Comment by johanholmerin** [comment]
No, it does not. The limited lifespan of service workers make them unsuitable for long-running tasks/connection. You can use the polyfill to set up a connection in a service worker(check out [worker.js](https://github.com/johanholmerin/worker-webrtc/blob/master/worker.js) and [window.js](https://github.com/johanholmerin/worker-webrtc/blob/master/window.js)), but if the service worker is terminated you will lose the references.

If you want to serve files through the service worker with data you have received through WebRTC, I recommend you handle that [manually with postMessage](https://github.com/johanholmerin/browsercast/blob/master/sw.js) instead of using this polyfill, which is supposed to be transparent.

**Comment by JiaJiaJiang** [comment]
The 'postMessage' link's code helps, thanks for the advice.
